! fix build fail/error under java 9+/11+ of project cola-components
1. upgrade lombok to 1.18.16 and change scope to provided

build error under jdk 9+ caused by low version lombok:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project craftsman-domain:
Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags

cc #143

2. add javax.annotation:javax.annotation-api provided dependency

build error under jdk 11+:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cola-component-test-container: Compilation failure: Compilation failure:
[ERROR] .../COLA/cola-components/cola-component-test-container/src/main/java/com/alibaba/cola/test/TestExecutor.java:[13,24] package javax.annotation does not exist
[ERROR] .../COLA/cola-components/cola-component-test-container/src/main/java/com/alibaba/cola/test/TestExecutor.java:[134,66] cannot find symbol
[ERROR]   symbol:   class Resource
[ERROR]   location: class com.alibaba.cola.test.TestExecutor